### ISSUE TITLE
Can’t view Archived task 

### ISSUE THREAD

**Issue by ZambiBambi** [GrooveOtter/grooveotter-client#205] opened 2015-07-28 00:26 UTC
Not able to select the "Archive" section to view the archived tasks

**Comment by L8D** [comment] 2015-08-08 20:35
Can't reproduce on an iPhone 6 in Safari.

**Comment by Ryan-Parker** [comment] 2015-08-10 19:47
@L8D This seems to be resolved with last pull

**Comment by Ryan-Parker** [comment] 2015-08-25 20:24
@L8D This seems to be occurring again

**Closed as completed** 2016-01-31 22:15 UTC
Labels: mobile, critical, Safari, Chrome
