### ISSUE TITLE
Display Text Input

### ISSUE THREAD

**Issue by garrethdev** [GrooveOtter/grooveotter-client#16] opened 2015-04-12 17:43 UTC
Depending on whether the user has started the timer, the timer is ongoing, or they have finished a task the statement within the textbox will change. 

Criteria: 
1. Create the Ui to replicate the invision Document 
2. Create the hover state with the pencil 
3. Connect the statement (What are you working on?) to the correct state of the buttons 
4. Allow the user to edit the input

**Comment by L8D** [comment] 2015-04-15 22:35
Duplicate of #13

**Closed as completed by L8D** 2015-04-15 22:35 UTC
Labels: Feature
